{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "f6271174",
   "metadata": {},
   "source": [
    "## telegrambot (텔레그램봇)\n",
    "## 텔레그램봇과 파이썬과의 연동을 통한 자신만의 채팅봇 만드는 예제."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "37b1a6a7",
   "metadata": {},
   "source": [
    "#### 봇이름 : 닉네임Bot\n",
    "#### hjkbot\n",
    "#### hjkbotbot"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6f7c69ac",
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install python-telegram-bot"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2059f09e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import telegram\n",
    "# 파이썬으로 날짜시간 다루기\n",
    "import datetime as dt\n",
    "\n",
    "now = dt.datetime.now() # 현재 날짜시간 정보 추출"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "79869205",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'PM 03:51:04'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 형식문자열 : %H(24시), %M(분), %S(초), %p(오전/오후)\n",
    "now.strftime('%H:%M:%S')\n",
    "now.strftime('%p %I:%M:%S')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b34fd1a3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'2021-11-19 Fri Friday'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 형식문자열 : %Y(24시), %m(월), %d(일) %A(요일명), %a(단축요일명)\n",
    "now.strftime('%Y-%m-%d %a %A')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b7c973bc",
   "metadata": {},
   "source": [
    "### 로케일 설정을 바꿔 %p, %A가 한국어로 출력되게 하기 \n",
    "* setLocale 함수를 이용 \n",
    "* 한국 로케일은 'ko_KR.UTF-8'로 지정"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "aea785ec",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'2021-11-19 금 금요일'"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import locale\n",
    "locale.setlocale(locale.LC_ALL, 'ko_KR.UTF-8')\n",
    "\n",
    "now.strftime('%p %I:%M:%S')\n",
    "now.strftime('%Y-%m-%d %a %A')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "def09791",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 텔레그램 인증키 드록\n",
    "\n",
    "token = '2134287695:AAFCSqcvBhcV0afK7HDzzMbR1D07vKa5dbA'\n",
    "\n",
    "# 텔레그램 봇 객체 생성\n",
    "\n",
    "bot = telegram.Bot(token=token)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "dbf314d4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<telegram.message.Message at 0x17d5e069a40>"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 특정 대화상대에게 메세지 보내기 테스트\n",
    "# sendMessage(대상, 메세지)\n",
    "bot.sendMessage(chat_id='2088453585', text= 'Hello, World!!')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "16837b3a",
   "metadata": {},
   "source": [
    "###  로또 번호를 알려주는 텔레그램봇을 만들어봄\n",
    "\n",
    "* /lotto라고 입력하면 6개의 숫자 출력"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1342bb8c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "import time\n",
    "from telegram import Update\n",
    "from telegram.ext import Updater, CallbackContext\n",
    "from telegram.ext import MessageHandler\n",
    "from telegram.ext import CommandHandler\n",
    "from telegram.ext import Filters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "a6f2f8eb",
   "metadata": {},
   "outputs": [],
   "source": [
    "### 텔레그램 챗봇 응답처리 콜백함수\n",
    "### 콜백함수명(context, update)\n",
    "\n",
    "# 지금 만든 이것은 입력받은 메세지를 다시 출력하는 함수\n",
    "def reply_message(update, context): context.bot.send_message(text=update.message.text,chat_id=update.message.chat_id)\n",
    "    \n",
    "\n",
    "# '/lotto'라 입력했을때 로또 출력하는 함수\n",
    "def lotto_message(update, context):\n",
    "    lotto = random.sample(range(1, 45+1), 6)\n",
    "    update.message.reply_text( 'f 21,34,34,15,6: {lotto} ')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3bef57ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "# '/date'라 입력했을 때 현재날짜(년-월-일) 출력하는 함수\n",
    "def date_message(update, context):\n",
    "    now = dt.datetime.now()\n",
    "    date = now.strftime('%Y-%m-%d %A')\n",
    "    update.message.reply_text(f'오늘 날짜 : {date} ')    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "12073ac3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# '/time'라 입력했을 때 현재시간(시:분:초 오전/오후) 출력하는 함수\n",
    "def time_message(update, context):\n",
    "    now = dt.datetime.now()\n",
    "    time = now.strftime('%p %I:%M:%S')\n",
    "    update.message.reply_text(f'현재 시간 : {time} 🕰 ')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4aa99cdb",
   "metadata": {},
   "source": [
    "### 텔레그램 챗봇 서버 실행\n",
    " * 일종의 서버 형태로 실행되어야 문자열을 입력할때 적절하게 반응을 할 것이다. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "7efdfbe8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "텔레그램 RPA 서버 준비중...\n"
     ]
    }
   ],
   "source": [
    "print('텔레그램 RPA 서버 준비중...')\n",
    "updater = Updater(token)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "7c24eadb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 위에서 정의한 콜백함수들을 핸들러객체로 만든후\n",
    "# 챗봇서버에 등록\n",
    "# MessageHandler : 입력받은 텍스트를 그대로 처리할 때 사용할 콜백함수를 호출하는 핸들러\n",
    "\n",
    "# CommandHandler : 특정문자열 입력시 지정한 콜백함수 호출 \n",
    "# CommandHandler(명령, 콜백함수)\n",
    "# addHandler : 생성한 핸들러 객체를 챗봇서버에 등록함.\n",
    "\n",
    "\n",
    "# 핸들러 정의\n",
    "reply_handler = MessageHandler(Filters.text, reply_message)\n",
    "\n",
    "lotto_handler = CommandHandler('lotto', lotto_message)\n",
    "\n",
    "date_handler = CommandHandler('date', date_message)\n",
    "time_handler = CommandHandler('time', time_message)\n",
    "\n",
    "\n",
    "\n",
    "# 핸들러 등록\n",
    "updater.dispatcher.add_handler(lotto_handler)\n",
    "\n",
    "updater.dispatcher.add_handler(date_handler)\n",
    "updater.dispatcher.add_handler(time_handler)\n",
    "\n",
    "updater.dispatcher.add_handler(reply_handler)\n",
    "# updater.dispatcher.add_handler(lotto_handler)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3e13d2d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "텔레그램 RPA 서버 실행중...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\TJ\\AppData\\Local\\Temp/ipykernel_9916/3897569799.py:4: TelegramDeprecationWarning: The argument `clean` of `start_polling` is deprecated. Please use `drop_pending_updates` instead.\n",
      "  updater.start_polling(\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\TJ\\anaconda3\\envs\\HJK\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "# 챗봇서버 가동\n",
    "\n",
    "print('텔레그램 RPA 서버 실행중...')\n",
    "updater.start_polling(\n",
    "                timeout=3, clean=True)\n",
    "updater.idle()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e974d54",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 현재 시간으로 맞춰주는 함수.\n",
    "\n",
    "date -s '2021-11-19 15:51'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5619e16c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
